package Modelos;
// Generated 11-nov-2015 20:37:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Embarazo generated by hbm2java
 */
public class Embarazo  implements java.io.Serializable {


     private Integer idEmbarazo;
     private Madres madres;
     private Date fechaPosibleDeParto;
     private Date fechaPosibleDeEmbarazo;
     private String obstreticos;
     private Set controleses = new HashSet(0);

    public Embarazo() {
    }

	
    public Embarazo(Madres madres, Date fechaPosibleDeParto, Date fechaPosibleDeEmbarazo, String obstreticos) {
        this.madres = madres;
        this.fechaPosibleDeParto = fechaPosibleDeParto;
        this.fechaPosibleDeEmbarazo = fechaPosibleDeEmbarazo;
        this.obstreticos = obstreticos;
    }
    public Embarazo(Madres madres, Date fechaPosibleDeParto, Date fechaPosibleDeEmbarazo, String obstreticos, Set controleses) {
       this.madres = madres;
       this.fechaPosibleDeParto = fechaPosibleDeParto;
       this.fechaPosibleDeEmbarazo = fechaPosibleDeEmbarazo;
       this.obstreticos = obstreticos;
       this.controleses = controleses;
    }
   
    public Integer getIdEmbarazo() {
        return this.idEmbarazo;
    }
    
    public void setIdEmbarazo(Integer idEmbarazo) {
        this.idEmbarazo = idEmbarazo;
    }
    public Madres getMadres() {
        return this.madres;
    }
    
    public void setMadres(Madres madres) {
        this.madres = madres;
    }
    public Date getFechaPosibleDeParto() {
        return this.fechaPosibleDeParto;
    }
    
    public void setFechaPosibleDeParto(Date fechaPosibleDeParto) {
        this.fechaPosibleDeParto = fechaPosibleDeParto;
    }
    public Date getFechaPosibleDeEmbarazo() {
        return this.fechaPosibleDeEmbarazo;
    }
    
    public void setFechaPosibleDeEmbarazo(Date fechaPosibleDeEmbarazo) {
        this.fechaPosibleDeEmbarazo = fechaPosibleDeEmbarazo;
    }
    public String getObstreticos() {
        return this.obstreticos;
    }
    
    public void setObstreticos(String obstreticos) {
        this.obstreticos = obstreticos;
    }
    public Set getControleses() {
        return this.controleses;
    }
    
    public void setControleses(Set controleses) {
        this.controleses = controleses;
    }




}


