package Modelos;
// Generated 11-nov-2015 20:37:18 by Hibernate Tools 4.3.1



/**
 * Familiares generated by hbm2java
 */
public class Familiares  implements java.io.Serializable {


     private Integer idFamiliar;
     private Madres madres;
     private String nombres;
     private String apellidos;
     private String telefono;
     private String documento;
     private String residencia;
     private String tipo;
     private String direccion;

    public Familiares() {
    }

	
    public Familiares(Madres madres, String nombres, String apellidos, String telefono, String documento, String residencia, String tipo) {
        this.madres = madres;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.documento = documento;
        this.residencia = residencia;
        this.tipo = tipo;
    }
    public Familiares(Madres madres, String nombres, String apellidos, String telefono, String documento, String residencia, String tipo, String direccion) {
       this.madres = madres;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.documento = documento;
       this.residencia = residencia;
       this.tipo = tipo;
       this.direccion = direccion;
    }
   
    public Integer getIdFamiliar() {
        return this.idFamiliar;
    }
    
    public void setIdFamiliar(Integer idFamiliar) {
        this.idFamiliar = idFamiliar;
    }
    public Madres getMadres() {
        return this.madres;
    }
    
    public void setMadres(Madres madres) {
        this.madres = madres;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


