package Modelos;
// Generated 11-nov-2015 20:37:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Madres generated by hbm2java
 */
public class Madres  implements java.io.Serializable {


     private Integer idMadre;
     private Residencias residencias;
     private Seguridades seguridades;
     private String nombres;
     private String apellidos;
     private String telefono;
     private String documento;
     private String direccion;
     private Date fechaDeNacimento;
     private Set familiareses = new HashSet(0);
     private Set embarazos = new HashSet(0);

    public Madres() {
    }

	
    public Madres(Residencias residencias, Seguridades seguridades, String nombres, String apellidos, String telefono, String documento, Date fechaDeNacimento) {
        this.residencias = residencias;
        this.seguridades = seguridades;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.documento = documento;
        this.fechaDeNacimento = fechaDeNacimento;
    }
    public Madres(Residencias residencias, Seguridades seguridades, String nombres, String apellidos, String telefono, String documento, String direccion, Date fechaDeNacimento, Set familiareses, Set embarazos) {
       this.residencias = residencias;
       this.seguridades = seguridades;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.documento = documento;
       this.direccion = direccion;
       this.fechaDeNacimento = fechaDeNacimento;
       this.familiareses = familiareses;
       this.embarazos = embarazos;
    }
   
    public Integer getIdMadre() {
        return this.idMadre;
    }
    
    public void setIdMadre(Integer idMadre) {
        this.idMadre = idMadre;
    }
    public Residencias getResidencias() {
        return this.residencias;
    }
    
    public void setResidencias(Residencias residencias) {
        this.residencias = residencias;
    }
    public Seguridades getSeguridades() {
        return this.seguridades;
    }
    
    public void setSeguridades(Seguridades seguridades) {
        this.seguridades = seguridades;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechaDeNacimento() {
        return this.fechaDeNacimento;
    }
    
    public void setFechaDeNacimento(Date fechaDeNacimento) {
        this.fechaDeNacimento = fechaDeNacimento;
    }
    public Set getFamiliareses() {
        return this.familiareses;
    }
    
    public void setFamiliareses(Set familiareses) {
        this.familiareses = familiareses;
    }
    public Set getEmbarazos() {
        return this.embarazos;
    }
    
    public void setEmbarazos(Set embarazos) {
        this.embarazos = embarazos;
    }




}


